openapi: 3.0.0
info:
  title: Smart Home Automation
  version: '1.0'
  description: Documentazione dell'API esposta dal backend di SHA. Progetto di Laboratorio di Progettazione. Marco Belotti, Francesco Bombarda, Antonio Vivace.
paths:
  /auth:
    post:
      summary: Return JWT token
      operationId: api.login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /requestPasswordReset:
    post:
      summary: Return JWT token
      operationId: api.reset_password_request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username_mobile:
                  type: string
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /resetPassword/{resetToken}:
    post:
      summary: Return JWT token
      operationId: api.reset_password
      parameters:
        - name: resetToken
          in: path
          description: Reset token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                newPassword:
                  type: string
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /delete/{objtype}/{id}:
    delete:
      summary: Elimina un'entità dalla configurazione del sistema.
      operationId: api.delete_object
      parameters:
        - name: id
          in: path
          description: Reset token
          required: true
          schema:
            type: string
        - name: objtype
          in: path
          description: Reset token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response
      security:
        - jwt: ['secret']
  /get-topics:
    get:
      summary: Restituisce l'elenco di tutti i topic associati ad attuaturi del tipo specificato
      operationId: api.get_topics
      responses:
        '200':
          description: Response
      security:
        - jwt: ['secret']
  /publish/{id}/{value}:
    post:
      summary: Publish
      operationId: api.mqtt_publish
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
        - name: value
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response
      security:
        - jwt: ['secret']
  /overview:
    get:
      summary: Publish
      operationId: api.overview
      responses:
        '200':
          description: Response
      security:
        - jwt: ['secret']
  /update-device:
    put:
      summary: Update device
      operationId: api.update_device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                old-id:
                  type: string
                description:
                  type: string
                type:
                  type: string
                pin:
                  type: number
                stanza:
                  type: number
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string
      security:
        - jwt: ['secret']
  /add-device:
    post:
      summary: Add device
      operationId: api.add_device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
                type:
                  type: string
                pin:
                  type: number
                stanza:
                  type: number
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string
      security:
        - jwt: ['secret']
  /add-stanza:
    post:
      summary: Add device
      operationId: api.add_stanza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                piano_id:
                  type: number
                description:
                  type: string
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string  
      security:
        - jwt: ['secret']
  /add-piano:
    post:
      summary: Add stanza
      operationId: api.add_piano
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string  
      security:
        - jwt: ['secret']
  /verify-token:
    get:
      summary: Return secret string
      operationId: api.get_secret
      responses:
        '200':
          description: secret response
          content:
            'text/plain':
              schema:
                type: string
      security:
      - jwt: ['secret']

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: api.decode_token
