openapi: 3.0.0
info:
  title: Smart Home Automation
  version: '1.0'
  description: Documentazione dell'API esposta dal backend di SHA. Progetto di Laboratorio di Progettazione. Marco Belotti, Francesco Bombarda, Antonio Vivace.
paths:
  /auth:
    post:
      summary: Return JWT token
      operationId: api.login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /get-topics:
    get:
      summary: Restituisce l'elenco di tutti i topic associati ad attuatori di tipo lampada
      operationId: api.get_topics
      responses:
        '200':
          description: Response
  /publish/{id}/{value}:
    get:
      summary: Publish
      operationId: api.mqtt_publish
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
        - name: value
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response
  /overview:
    get:
      summary: Publish
      operationId: api.overview
      responses:
        '200':
          description: Response
  /add-device:
    post:
      summary: Add device
      operationId: api.add_device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                topic:
                  type: string
                description:
                  type: string
                type:
                  type: string
                pin:
                  type: number
                stanza_id:
                  type: number
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string
  /add-stanza:
    post:
      summary: Add device
      operationId: api.add_stanza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                piano_id:
                  type: number
                description:
                  type: string
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string  
#      security:
#        - jwt: ['secret']
  /add-piano:
    post:
      summary: Add stanza
      operationId: api.add_stanza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string  
#      security:
#        - jwt: ['secret']
  /verify-token:
    get:
      summary: Return secret string
      operationId: api.get_secret
      responses:
        '200':
          description: secret response
          content:
            'text/plain':
              schema:
                type: string
      security:
      - jwt: ['secret']

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: api.decode_token
