openapi: 3.0.0
info:
  title: Smart Home Automation
  version: '1.0'
  description: Documentazione dell'API esposta dal backend di SHA. Progetto di Laboratorio di Progettazione. Marco Belotti, Francesco Bombarda, Antonio Vivace.
paths:
  /auth:
    post:
      summary: Return JWT token
      operationId: api.login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /verify-token:
    get:
      summary: Return secret string
      operationId: api.get_secret
      responses:
        '200':
          description: secret response
          content:
            'text/plain':
              schema:
                type: string
      security:
      - jwt: ['secret']

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: api.decode_token
