openapi: 3.0.0
info:
  title: Smart Home Automation
  version: '1.0'
  description: Documentazione e specifica OpenAPI 3 dell'API esposta da SHA.
paths:
  /auth:
    post:
      summary: Autentica l'utente con le credenziali fornite, fornendo un JWT token
      operationId: api.login
      tags:
        - Autenticazione
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /requestPasswordReset:
    post:
      summary: Richiedi il ripristino delle credenziali per l'utente con la mail o cellulare forniti
      operationId: api.reset_password_request
      tags:
        - Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username_mobile:
                  type: string
      responses:
        '200':
          description: Esito
          content:
            'text/plain':
              schema:
                type: string
  /resetPassword/{resetToken}:
    post:
      summary: Consuma il token per ripristinare la password
      operationId: api.reset_password
      tags:
        - Account
      parameters:
        - name: resetToken
          in: path
          description: Reset token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                newPassword:
                  type: string
      responses:
        '200':
          description: Esito
          content:
            'text/plain':
              schema:
                type: string
  /delete/{objtype}/{id}:
    delete:
      summary: Elimina un'entità (Piano, Stanza o Attuatore) dalla configurazione del sistema
      operationId: api.delete_object
      tags:
        - Sistema
      parameters:
        - name: id
          in: path
          description: ID
          required: true
          schema:
            type: string
        - name: objtype
          in: path
          description: Tipo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response
      security:
        - jwt: ['secret']
  /get-topics:
    get:
      tags:
        - Sistema
      summary: Restituisce l'elenco di tutti i topic associati ad attuaturi del tipo specificato
      operationId: api.get_topics
      responses:
        '200':
          description: Response
      security:
        - jwt: ['secret']
  /publish/{id}/{value}:
    post:
      summary: Pubblica il valore specificato sul topic MQTT corrispondente all'ID fornito 
      operationId: api.mqtt_publish
      tags:
        - Sistema
      parameters:
        - name: id
          in: path
          description: ID attuatore
          required: true
          schema:
            type: string
        - name: value
          in: path
          description: Valore
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Esito
      security:
        - jwt: ['secret']
  /overview:
    get:
      tags:
        - Sistema
      summary: Ottieni una serializzazione JSON completa della configurazione del sistema in ogni sua parte
      operationId: api.overview
      responses:
        '200':
          description: Response
      security:
        - jwt: ['secret']
  /activate-user/{user_id}:
    put:
      tags:
        - Account
      summary: Attiva l'account specificato (da utente amministratore)
      parameters:
        - name: user_id
          in: path
          description: ID dell'utente da attivare
          required: true
          schema:
            type: string
      operationId: api.activate_user
      responses:
        '200':
          description: Esito
          content:
            'text/plain':
              schema:
                type: string
      security:
        - jwt: ['secret']
  /update-device:
    put:
      tags:
        - Sistema
      summary: Modifica i dettagli di un attuatore
      operationId: api.update_device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                old-id:
                  type: string
                description:
                  type: string
                type:
                  type: string
                pin:
                  type: number
                stanza:
                  type: number
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string
      security:
        - jwt: ['secret']
  /add-device:
    post:
      tags:
        - Sistema
      summary: Aggiungi un attuatore alla configurazione di sistema
      operationId: api.add_device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
                type:
                  type: string
                pin:
                  type: number
                stanza:
                  type: number
      responses:
        '200':
          description: Outcome
          content:
            'text/plain':
              schema:
                type: string
      security:
        - jwt: ['secret']
  /add-stanza:
    post:
      tags:
        - Sistema
      summary: Aggiungi una stanza alla configurazione di sistema
      operationId: api.add_stanza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                piano_id:
                  type: number
                description:
                  type: string
      responses:
        '200':
          description: Esito
          content:
            'text/plain':
              schema:
                type: string  
      security:
        - jwt: ['secret']
  /add-piano:
    post:
      tags:
        - Sistema
      summary: Aggiungi un piano alla configurazione di sistema
      operationId: api.add_piano
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
      responses:
        '200':
          description: Esito
          content:
            'text/plain':
              schema:
                type: string  
      security:
        - jwt: ['secret']
  /verify-token:
    get:
      tags:
        - Autenticazione
      summary: Verifica la validità del token fornito, restituendo dettagli sull'utente per cui questo claim è valido
      operationId: api.get_secret
      responses:
        '200':
          description: secret response
          content:
            'text/plain':
              schema:
                type: string
      security:
      - jwt: ['secret']

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: api.decode_token
